name: TNTFireworks
version: '${version}'
main: me.loule.tntfireworks.Main
api-version: '1.21'
description: Transforms TNT explosions into beautiful low-flying fireworks without damaging blocks. Creates chain reactions with nearby TNT for spectacular visual effects.
commands:
  tntfireworks:
    description: Main command for TNTFireworks plugin
    usage: /tntfireworks [reload|update|check|restart]
    aliases: [tntfw]
permissions:
  tntfireworks.reload:
    description: Allows reloading the plugin configuration
    default: op
  tntfireworks.update:
    description: Allows checking for and applying plugin updates
    default: op
  tntfireworks.restart:
    description: Allows restarting the server after an update
    default: op
